name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TEST_DIRECTORY: test

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: .NET Setup
        uses: zyactions/dotnet-setup@v1

      - name: .NET Restore
        uses: ./
        with:
          working-directory: ${{ env.TEST_DIRECTORY }}

      - name: .NET Restore Project
        uses: ./
        with:
          working-directory: ${{ env.TEST_DIRECTORY }}
          workspace: Test.csproj
