name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0

      - name: .NET Setup
        uses: zyactions/dotnet-setup@v1.0.0

      - name: .NET Restore
        uses: ./
        with:
          workspace: test

      - name: .NET Restore Project
        uses: ./
        with:
          workspace: test/Test.csproj
